name: PixelOS_Kernel_CI-aston

on:
  workflow_dispatch:

jobs:
  PixelOS_Kernel_CI:
    name: PixelOS Kernel CI (aston)
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Clone Kernel and Dependencies
      run: |
        git clone https://github.com/MangTianYa/android_kernel_oneplus_sm8550.git 
        git clone https://github.com/PixelOS-Devices/kernel_oneplus_sm8550-modules.git 
    
    - name: Setup release name
      run: |
        rm -rf ${GITHUB_WORKSPACE}/*.zip
        SUBLEVEL=$(grep "^SUBLEVEL =" Makefile | awk '{print $3}')
        REL_NAME="OP12R-v5.15.${SUBLEVEL}-$(date +"%Y%m%d")"
        echo "REL_NAME=${REL_NAME}" >> $GITHUB_ENV

    - name: Build Kernel with ksu
      run: |
        ./build.sh 
        mv kernel.zip ${GITHUB_WORKSPACE}/ksu.zip
        git clean -fdx && find . -mindepth 1 -maxdepth 1 -type d -exec test -d "{}/.git" \; -print | xargs rm -rf && git reset --hard
        cd -
