name: PixelOS_Kernel_CI-aston

on:
  workflow_dispatch:

jobs:
  PixelOS_Kernel_CI:
    name: PixelOS Kernel CI (aston)
    runs-on: self-hosted
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Clone Kernel and Dependencies
      run: |
        git clone https://github.com/PixelOS-Devices/kernel_oneplus_sm8550.git --depth=1 -b fifteen kernel/oneplus/sm8550
        git clone https://github.com/PixelOS-Devices/kernel_oneplus_sm8550-modules.git --depth=1 -b fifteen kernel/oneplus/sm8550-modules
    
    - name: Setup release name
      run: |
        cd kernel/oneplus/sm8550
        SUBLEVEL=$(grep "^SUBLEVEL =" Makefile | awk '{print $3}')
        REL_NAME="OP12R-v5.15.${SUBLEVEL}-$(date +"%Y%m%d")"
        echo "REL_NAME=${REL_NAME}" >> $GITHUB_ENV

    - name: Build base kernel
      run: |
        cd kernel/oneplus/sm8550
        build_sm8550
        mv kernel.zip ${HOME}/kernel.zip
        git clean -fdx && find . -mindepth 1 -maxdepth 1 -type d -exec test -d "{}/.git" \; -print | xargs rm -rf && git reset --hard
        cd -

    - name: Build Kernel with ksu
      run: |
        cd kernel/oneplus/sm8550
        build_sm8550 --ksu
        mv kernel.zip ${HOME}/ksu.zip
        git clean -fdx && find . -mindepth 1 -maxdepth 1 -type d -exec test -d "{}/.git" \; -print | xargs rm -rf && git reset --hard
        cd -

    - name: Build Kernel with ksu-next
      run: |
        cd kernel/oneplus/sm8550
        build_sm8550 --ksu-next
        mv kernel.zip ${HOME}/ksu-next.zip
        git clean -fdx && find . -mindepth 1 -maxdepth 1 -type d -exec test -d "{}/.git" \; -print | xargs rm -rf && git reset --hard
        cd -

    - name: Build Kernel with ksu-next + susfs
      run: |
        cd kernel/oneplus/sm8550
        build_sm8550 --ksu-next-susfs
        mv kernel.zip ${HOME}/ksu-next-susfs.zip
        git clean -fdx && find . -mindepth 1 -maxdepth 1 -type d -exec test -d "{}/.git" \; -print | xargs rm -rf && git reset --hard
        cd -

    - name: Create GitHub Release
      run: |
        gh release create "$REL_NAME" --title "$REL_NAME" --notes "" ${HOME}/kernel.zip ${HOME}/ksu.zip ${HOME}/ksu-next.zip ${HOME}/ksu-next-susfs.zip
